#!/bin/bash

VERSION="0.1"

scripts_dir="scripts"

case "$1" in
	register)
		
		shift
		python3 ${scripts_dir}/register_node.py $@
		exit $?
		;;
	
	ping)

		shift
		python3 ${scripts_dir}/ping.py $1
		exit $?
		;;

	-v|--version)		
		
		echo "DeployBox v$VERSION"
		;;

	 *|-h|--help)

	 	echo "TODO: help output"
		;;
esac

exit 0
