#!/bin/bash

VERSION="0.1"

scripts_dir="scripts"

case "$1" in
	register)
		
		shift
		python3 ${scripts_dir}/register_node.py $@
		exit $?
		;;
	
	ping)

		shift
		python3 ${scripts_dir}/ping.py $1
		exit $?
		;;

	login)

		shift
		if ( python3 ${scripts_dir}/ping.py $1 1> /dev/null )
		then
			login_vars="$(python3 ${scripts_dir}/set_login_vars.py $1)"
			echo $login_vars
		fi
		;;

	-v|--version)		
		
		echo "DeployBox v$VERSION"
		;;

	 *|-h|--help)

	 	echo "TODO: help output"
		;;
esac

exit 0
